spring:
  application:
    name: lookmax-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lookmaxDB
    username: postgres
    password: admin1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

firebase:
  service-account-file: ${FIREBASE_SERVICE_ACCOUNT_FILE:firebase-service-account.json}
  service-account-key: ${FIREBASE_SERVICE_ACCOUNT_KEY:}
  project-id: ${FIREBASE_PROJECT_ID:votre-projet-id}
